models/Category.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "category".
 *
 * @property int $id
 * @property string $name
 * @property int $status
 */
class Category extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'category';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['status'], 'integer'],
            [['name'], 'string', 'max' => 100],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Name'),
            'status' => Yii::t('app', 'Status'),
            'created_by' => Yii::t('app', 'Created By'),
            'created_date' => Yii::t('app', 'Created Date'),
            'updated_by' => Yii::t('app', 'Updated By'),
            'updated_date' => Yii::t('app', 'Updated Date'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(User::className(), ['id' => 'created_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUpdatedBy()
    {
        return $this->hasOne(User::className(), ['id' => 'updated_by']);
    }

    /**
     * @inheritdoc
     */
    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
            // Place your custom code here
            if ($this->isNewRecord) {
                // new record
                $this->created_by = (Yii::$app->user->id) ? Yii::$app->user->id: '';
                $this->updated_by = (Yii::$app->user->id) ? Yii::$app->user->id: '';
                $this->created_date = new \yii\db\Expression('NOW()');
            }
            else {
                // update record
                $this->updated_by = (Yii::$app->user->id) ? Yii::$app->user->id: '';
                $this->updated_date = new \yii\db\Expression('NOW()');
            }

            return true;
        } else {
            return false;
        }
    }
}

controllers/CategoryController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Category;
use app\models\CategorySearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CategoryController implements the CRUD actions for Category model.
 */
class CategoryController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Category models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CategorySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Category model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Category model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Category();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Category model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Category model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Category model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Category the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Category::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

views/category/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

use app\models\BaseFunctions;

/* @var $this yii\web\View */
/* @var $model app\models\Category */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="category-form">
    <?php $form = ActiveForm::begin(); ?>
    
    <div class="box box-success">
        <div class="box-header with-border">
            <h3 class="box-title"><?php echo ($model->isNewRecord) ? Yii::t('app', 'Create New Category'):Yii::t('app', 'Category Update: '. $model->name); ?></h3>
        </div><!-- box-header -->

        <div class="box-body">

            <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

            <?php if(!$model->isNewRecord) { ?>
                <?= $form->field($model, 'status')->dropDownList(BaseFunctions::dropDownStatus()); ?>
            <?php } ?>            

        </div><!-- box-body -->

        <div class="box-footer">
            <div class="form-group">
                <a href="<?php echo Yii::$app->request->referrer; ?>" class="btn btn-warning"><i class="fa fa-arrow-left"></i> <?php echo Yii::t('app', 'Back'); ?></a>

                <?= Html::submitButton($model->isNewRecord ? '<i class="fa fa-plus"></i> '.Yii::t('app', 'Create') : '<i class="fa fa-save"></i> '.Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
            </div>
        </div><!-- box-footer -->

    </div><!-- box -->
    
    <?php ActiveForm::end(); ?>
</div>

views/category/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;

use app\models\BaseFunctions;

/* @var $this yii\web\View */
/* @var $model app\models\CategorySearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="category-search">
    <div class="row">
        <div class="col-md-12">

            <?php $form = ActiveForm::begin([
                'action' => ['index'],
                'method' => 'get',
            ]); ?>

            <div class="col-md-7">
                <?= $form->field($model, 'name') ?>
            </div>

            <div class="col-md-3">
                <?= $form->field($model, 'status')->dropDownList(BaseFunctions::dropDownStatus()); ?>
            </div>

            <div class="col-md-2">
                <label>&nbsp;</label><br>
                <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
                <?= Html::a(Yii::t('app', 'Reset'), ['index'], ['class' => 'btn btn-default']) ?>

            </div>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/category/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Category */

$this->title = Yii::t('app', 'Categories');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Categories'), 'url' => ['index']];
$this->params['breadcrumbs'][] = Yii::t('app', 'Create');
?>
<div class="category-create">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/category/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

use app\models\BaseFunctions;

/* @var $this yii\web\View */
/* @var $searchModel app\models\CategorySearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Categories');
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="box box-success box-solid collapsed-box">
    <div class="box-header with-border">
        <h3 class="box-title"><?= Yii::t('app', 'Search Criteria') ?></h3>

        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i></button>
        </div>
        <!-- /.box-tools -->
    </div>
    <!-- /.box-header -->

    <div class="box-body" style="display: none;">
        <?= $this->render('_search', [
            'model' => $searchModel
        ]) ?>
    </div>
    <!-- /.box-body -->
</div>

<div class="category-index">
    <div class="box box-success">
        <div class="box-header with-border">
            <h3 class="box-title pull-right">
                <?= Html::a('<span class="fa fa-plus"></span> Create', ['create'], ['class' => 'btn btn-success']) ?>
            </h3>
        </div><!-- box-header -->

        <div class="box-body table-responsive">
            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                // 'summary' => "Memaparkan {begin} - {end} daripada {totalCount} rekod",
                'columns' => [
                    ['class' => 'yii\grid\SerialColumn',
                        'headerOptions' => ['class' => 'text-center', 'style' => 'width:5%'],
                        'contentOptions' => ['class' => 'text-center'],
                    ],

                    'name',

                    [
                        'header'=>'Status',
                        'headerOptions' => ['class' => 'text-center', 'style' => 'width:12%'],
                        'contentOptions' => ['class' => 'text-center'],
                        'attribute' => 'status',
                        'value' => function($model) {   
                            return BaseFunctions::status($model->status);
                        },
                        'format'=>'html',
                    ],

                    [
                        'class' => 'yii\grid\ActionColumn',
                        'header'=>'Action',
                        'headerOptions' => ['class' => 'text-center', 'style' => 'width:15%'],
                        'contentOptions' => ['class' => 'text-center'],
                        'template' => '{view} {update} {delete}', //
                        'buttons' => [
                            'update' => function ($url, $model) {     
                                return Html::a('<span class="glyphicon glyphicon-pencil"></span>', $url, [
                                    'title' => Yii::t('yii', 'Update'),
                                    'class'=>'btn btn-warning btn btn-xs',
                                ]);   
                            },
                            'view' => function ($url, $model) {     
                                return Html::a('<span class="glyphicon glyphicon-search"></span>', $url, [
                                    'title' => Yii::t('yii', 'View'),
                                    'class'=>'btn btn-info btn-xs',
                                ]);   
                            },
                            'delete' => function ($url, $model) {
                                return Html::a('<span class="glyphicon glyphicon-trash"></span>', $url, [
                                    'title' => Yii::t('yii', 'Delete'),
                                    'class'=>'btn btn-danger btn-xs',
                                    'data-confirm' => Yii::t('yii', 'Are you sure you want to delete this data?'),
                                    'data-method' => 'post',
                                    'data-pjax' => '0',
                                ]);
                            }
                        ],
                    ],
                ],
            ]); ?>
        </div><!-- box-body -->
    </div><!-- box -->

</div>

views/category/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Category */

$this->title = Yii::t('app', 'Categories');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Categories'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="category-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/category/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

use app\models\BaseFunctions;

/* @var $this yii\web\View */
/* @var $model app\models\Category */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Categories'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<style type="text/css">
    table.detail-view th {
        width: 25%;
    }
    table.detail-view td {
        width: 75%;
    }
</style>

<div class="category-view">

    <div class="box box-success">
        <div class="box-header with-border">
            <h3 class="box-title"><?= Yii::t('app', 'Category Detail: '. $model->name); ?></h3>
        </div><!-- box-header -->
        <div class="box-body">
            <?= DetailView::widget([
                'model' => $model,
                'attributes' => [
                    'name',
                    [   
                        'attribute' => 'status',
                        'value' => function($model) { 
                            return BaseFunctions::status($model->status);
                        },
                        'format'=>'html',
                    ],
                ],
            ]) ?>

            <div><i><small><br>
                <?= Yii::t('app', 'Updated by '); echo (isset($model->updatedBy->profile)) ? $model->updatedBy->profile->name:'-'; echo Yii::t('app', ' on '); echo date('d-M-Y h:i A', strtotime($model->updated_date)) ?>
            </small></i></div>
        </div><!-- box-body -->

        <div class="box-footer">

            <p>
                <?= Html::a('<i class="fa fa-arrow-left"></i> Back', ['index'], ['class' => 'btn btn-warning']) ?>
                <?= Html::a('<i class="fa fa-cog"></i> Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
                <?= Html::a('<i class="fa fa-trash"></i> Delete', ['delete', 'id' => $model->id], [
                    'class' => 'btn btn-danger',
                    'data' => [
                        'confirm' => 'Are you sure to delete this record?',
                        'method' => 'post',
                    ],
                ]) ?>
            </p>
        </div><!-- box-footer -->
    </div><!-- box -->    

</div>