models/Place.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "place".
 *
 * @property int $id
 * @property string $name
 * @property string $contact_no
 * @property string $duration
 * @property string $address1
 * @property string $address2
 * @property string $address3
 * @property string $poscode
 * @property string $city
 * @property int $state_id
 * @property string $price_range
 * @property int $parking_type_id
 * @property string $detail
 * @property int $spending_type_id
 * @property double $latitude
 * @property double $longitude
 * @property string $url
 * @property int $status
 * @property int $created_by
 * @property string $created_date
 * @property int $updated_by
 * @property string $updated_date
 *
 * @property ParkingType $parkingType
 * @property States $state
 * @property PlaceCategory[] $placeCategories
 * @property PlaceImage[] $placeImages
 * @property PlaceIslamicElement[] $placeIslamicElements
 * @property PlaceOperationHour[] $placeOperationHours
 */
class Place extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'place';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'address1', 'poscode', 'city', 'state_id', 'parking_type_id', 'spending_type_id', 'latitude', 'longitude'], 'required'],
            [['duration', 'created_date', 'updated_date'], 'safe'],
            [['state_id', 'parking_type_id', 'spending_type_id', 'status', 'created_by', 'updated_by'], 'integer'],
            [['price_range', 'detail', 'operating_remark'], 'string'],
            [['latitude', 'longitude'], 'number'],
            [['name', 'address1', 'address2', 'address3', 'url'], 'string', 'max' => 255],
            [['contact_no', 'poscode'], 'string', 'max' => 15],
            [['city'], 'string', 'max' => 100],
            [['parking_type_id'], 'exist', 'skipOnError' => true, 'targetClass' => ParkingType::className(), 'targetAttribute' => ['parking_type_id' => 'id']],
            [['state_id'], 'exist', 'skipOnError' => true, 'targetClass' => States::className(), 'targetAttribute' => ['state_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Place Name'),
            'contact_no' => Yii::t('app', 'Contact No'),
            'duration' => Yii::t('app', 'Estimate Duration'),
            'address1' => Yii::t('app', 'Address1'),
            'address2' => Yii::t('app', 'Address2'),
            'address3' => Yii::t('app', 'Address3'),
            'poscode' => Yii::t('app', 'Poscode'),
            'city' => Yii::t('app', 'City'),
            'state_id' => Yii::t('app', 'State'),
            'price_range' => Yii::t('app', 'Price Range'),
            'parking_type_id' => Yii::t('app', 'Parking Type'),
            'detail' => Yii::t('app', 'Detail'),
            'spending_type_id' => Yii::t('app', 'Visit Duration'),
            'latitude' => Yii::t('app', 'Latitude'),
            'longitude' => Yii::t('app', 'Longitude'),
            'url' => Yii::t('app', 'Url'),
            'operating_remark' => Yii::t('app', 'Operation Hour Remark'),
            'status' => Yii::t('app', 'Status'),
            'created_by' => Yii::t('app', 'Created By'),
            'created_date' => Yii::t('app', 'Created Date'),
            'updated_by' => Yii::t('app', 'Updated By'),
            'updated_date' => Yii::t('app', 'Updated Date'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getParkingType()
    {
        return $this->hasOne(ParkingType::className(), ['id' => 'parking_type_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSpendingType()
    {
        return $this->hasOne(SpendingType::className(), ['id' => 'spending_type_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getState()
    {
        return $this->hasOne(States::className(), ['id' => 'state_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPlaceCategories()
    {
        return $this->hasOne(PlaceCategory::className(), ['place_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPlaceImages()
    {
        return $this->hasMany(PlaceImage::className(), ['place_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPlaceIslamicElements()
    {
        return $this->hasMany(PlaceIslamicElement::className(), ['place_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPlaceOperationHours()
    {
        return $this->hasMany(PlaceOperationHour::className(), ['place_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(User::className(), ['id' => 'created_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUpdatedBy()
    {
        return $this->hasOne(User::className(), ['id' => 'updated_by']);
    }

    /**
     * @inheritdoc
     */
    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
            // Place your custom code here
            if ($this->isNewRecord) {
                // new record
                $this->created_by = (Yii::$app->user->id) ? Yii::$app->user->id: '';
                $this->updated_by = (Yii::$app->user->id) ? Yii::$app->user->id: '';
                $this->created_date = new \yii\db\Expression('NOW()');
            }
            else {
                // update record
                $this->updated_by = (Yii::$app->user->id) ? Yii::$app->user->id: '';
                $this->updated_date = new \yii\db\Expression('NOW()');
            }

            return true;
        } else {
            return false;
        }
    }
}

controllers/PlaceController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Place;
use app\models\PlaceSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;

use app\models\PlaceCategory;
use app\models\PlaceIslamicElement;
use app\models\PlaceImage;
use app\models\PlaceOperationHour;
use app\models\Model;
use app\models\Category;
use app\models\IslamicElements;

/**
 * PlaceController implements the CRUD actions for Place model.
 */
class PlaceController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Place models.
     * @return mixed
     */
    public function actionIndex()
    {   
        $status = Yii::$app->request->get('status');

        $searchModel = new PlaceSearch();
        $searchModel->status = $status;
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Place model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {   
        $model = $this->findModel($id);

        $placeCategories = PlaceCategory::find()->where(['place_id' => $id])->one();

        $placeElements = PlaceIslamicElement::find()->where(['place_id' => $id])->one();

        $operationHours = $model->placeOperationHours;

        $images = $model->placeImages;

        return $this->render('view', [
            'model' => $model,
            'placeCategories' => $placeCategories,
            'placeElements' => $placeElements,
            'operationHours' => $operationHours,
            'images' => $images
        ]);
    }

    /**
     * Creates a new Place model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Place();

        $placeCategories = new PlaceCategory();

        $placeElements = new PlaceIslamicElement();

        $placeImages = [new PlaceImage]; // for inserting multiple image

        $placeOperationHours[0] = new PlaceOperationHour;
        $placeOperationHours[1] = new PlaceOperationHour;
        $placeOperationHours[2] = new PlaceOperationHour;
        $placeOperationHours[3] = new PlaceOperationHour;
        $placeOperationHours[4] = new PlaceOperationHour;
        $placeOperationHours[5] = new PlaceOperationHour;
        $placeOperationHours[6] = new PlaceOperationHour;

        if ($model->load(Yii::$app->request->post())) { 

            $model->spending_type_id = 1;
            $model->status = 3;

            // place image
            $placeImages = Model::createMultiple(PlaceImage::className());
            Model::loadMultiple($placeImages, Yii::$app->request->post());
            foreach ($placeImages as $index => $image) {
                $image->detail = ($image->detail=='') ? '-':$image->detail;
                $imageFiles = \yii\web\UploadedFile::getInstance($image, "[{$index}]img");
                $image->img = $imageFiles;

            }

            // place operation hour
            $placeOperationHours = Model::createMultiple(PlaceOperationHour::className());
            Model::loadMultiple($placeOperationHours, Yii::$app->request->post());
            foreach ($placeOperationHours as $index => $hour) {
                $hour->day_id = ($hour->day_id=='') ? '-':$hour->day_id;
                $hour->start_time = ($hour->start_time=='') ? '-':$hour->start_time;
                $hour->end_time = ($hour->end_time=='') ? '-':$hour->end_time;

            }

            $valid = $model->validate();
            $valid = Model::validateMultiple($placeImages) && $valid;

            if ($valid) {
                $transaction = Yii::$app->db->beginTransaction();
                try {

                    if ($flag = $model->save(false)) {
                        foreach ($placeImages as $image) {

                            $upload_path = \Yii::getAlias('@app/web/upload');
                            if (!is_dir($upload_path)) {
                                mkdir($upload_path, 0777, true);
                            }

                            $place_image_path = \Yii::getAlias('@app/web/upload/place_image');
                            if (!is_dir($place_image_path)) {
                                mkdir($place_image_path, 0777, true);
                            }

                            $directory = $place_image_path . DIRECTORY_SEPARATOR . $model->id . DIRECTORY_SEPARATOR;

                            if (!is_dir($directory)) {
                                mkdir($directory,0777,true);
                            }

                            // if ada file
                            if($image->img) {

                                $uid = uniqid(time(), true);
                                $fileName = $uid . '.' . $image->img->extension;
                                $filePath = $directory . $fileName;
                                $fileSize = (string) $image->img->size;
                                $fileType = $image->img->type;
                                $placeId = $model->id;
                                $placeDetail = $image->detail;

                                if ($image->img->saveAs($filePath)) {
                                    $path = '/upload/place_image/' . $model->id . DIRECTORY_SEPARATOR . $fileName;

                                    // insert into table place image
                                    $image = new PlaceImage;
                                    $image->file_path = $path;
                                    $image->file_size = $fileSize;
                                    $image->file_type = $fileType;
                                    $image->file_name = $fileName;
                                    $image->place_id = $placeId; // set place id
                                    $image->detail = $placeDetail;

                                    if (!$image->save()) {
                                        print_r($image->errors);exit;
                                    }
                                }

                                if ($image->detail) {
                                    if (($flag = $image->save(false)) === false) {
                                        $transaction->rollBack();
                                        break;
                                    }
                                }
                            }

                        } // end foreach $placeImages

                        // insert into table place operation hour
                        foreach ($placeOperationHours as $hour) {

                            $hour->place_id = $model->id;
                            $hour->day_id = $hour->day_id;
                            $hour->start_time = date("H:i", strtotime($hour->start_time));
                            $hour->end_time = date("H:i", strtotime($hour->end_time));

                            if (!$hour->save()) {
                                print_r($hour->errors);exit;
                            }

                            if (($flag = $hour->save(false)) === false) {
                                $transaction->rollBack();
                                break;
                            }
                        }

                        // loop group category and simpan dalam string
                        $post_category = $_POST['PlaceCategory']['category_id'];
                        if(!empty($post_category)) {
                            $category_string = implode (",", $post_category);

                            $placeCategories->category_id = $category_string;
                            $placeCategories->place_id = $model->id;
                            $placeCategories->save();
                        }

                        // loop islamic element and simpan dalam string
                        $post_element = $_POST['PlaceIslamicElement']['islamic_element_id'];
                        if(!empty($post_element)) {
                            $element_string = implode (",", $post_element);

                            $placeElements->islamic_element_id = $element_string;
                            $placeElements->place_id = $model->id;
                            $placeElements->save();
                        }
                    }

                    if ($flag) {
                        $transaction->commit();

                        Yii::$app->getSession()->setFlash('success', Yii::t('app', 'New Place Added'));
                        return $this->redirect(['view', 'id' => $model->id]);

                    }

                } catch (Exception $e) {

                    $transaction->rollBack();

                }
            }
        }

        return $this->render('create', [
            'model' => $model,
            'placeCategories' => $placeCategories,
            'placeElements' => $placeElements,
            'placeImages' => (empty($placeImages)) ? [new PlaceImage] : $placeImages,
            'categories' => $this->getCategoryList(),
            'elements' => $this->getElementList(),
            'placeOperationHours' => (empty($placeOperationHours)) ? [new PlaceOperationHour] : $placeOperationHours
        ]);
    }

    /**
     * Updates an existing Place model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed

views/place/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;

use app\models\BaseFunctions;

/* @var $this yii\web\View */
/* @var $model app\models\PlaceSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="place-search">
    <div class="row">
        <div class="col-md-12">

            <?php $form = ActiveForm::begin([
                'action' => ['index'],
                'method' => 'get',
            ]); ?>

            <div class="col-md-4">
                <?= $form->field($model, 'name') ?>
            </div>

            <div class="col-md-3">
                <?= $form->field($model, 'state_id')->dropDownList(BaseFunctions::dropDownStates()); ?>
            </div>

            <div class="col-md-3">
                <?= $form->field($model, 'status')->dropDownList(BaseFunctions::dropDownStatusPlace()); ?>
            </div>

            <div class="col-md-2">
                <label>&nbsp;</label><br>
                <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
                <?= Html::a(Yii::t('app', 'Reset'), ['index'], ['class' => 'btn btn-default']) ?>

            </div>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/place/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Place */

$this->title = Yii::t('app', 'Create Place');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Places'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="place-create">

    <!-- <h1><?= Html::encode($this->title) ?></h1> -->

    <?= $this->render('_form', [
        'model' => $model,
        'placeCategories' => $placeCategories,
        'placeElements' => $placeElements,
        'placeImages' => $placeImages,
        'categories' => $categories,
        'elements' => $elements,
        'placeOperationHours' => $placeOperationHours
    ]) ?>

</div>

views/place/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Place */

$this->title = Yii::t('app', 'Update Place: ' . $model->name, [
    'nameAttribute' => '' . $model->name,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Places'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="place-update">

    <!-- <h1><?= Html::encode($this->title) ?></h1> -->

    <?= $this->render('_form', [
        'model' => $model,
        'placeCategories' => $placeCategories,
        'placeElements' => $placeElements,
        'placeImages' => $placeImages,
        'placeOperationHours' => $placeOperationHours,
        'categories' => $categories,
        'elements' => $elements,
    ]) ?>

</div>

views/place/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\helpers\Url;

use app\models\BaseFunctions;
use app\models\PlaceImage;
use app\models\Category;
use app\models\IslamicElements;

/* @var $this yii\web\View */
/* @var $model app\models\Place */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Places'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<?php $attribute_labels = $model->attributeLabels(); ?>

<div class="box box-success box-solid">
    <div class="box-header with-border">
        <h3 class="box-title"><i class="fa fa-street-view"></i>&nbsp;&nbsp;<?= Yii::t('app', 'Place Details') ?></h3>
        <div class="box-tools pull-right">
        </div>
    </div>
    <div class="table-responsive">

        <table class="table table-condensed table-bordered table-striped">
            <tr>
                <th width="15%"><?= $attribute_labels['name']; ?></th>
                <td width="35%"><?= (isset($model->name))?$model->name:'-'; ?></td>     
            
                <th width="15%"><?= $attribute_labels['duration'] ?></th>
                <td width="35%"><?= (isset($model->duration)) ? BaseFunctions::durations($model->duration):'-'; ?></td>
            </tr>
            <tr>
                <th width="15%"><?= Yii::t('app', 'Address') ?></th>
                <td width="35%"><?= BaseFunctions::address($model->id) ?></td>
            
                <th width="15%"><?= $attribute_labels['price_range'] ?></th>
                <td width="35%"><?= nl2br($model->price_range); ?></td>
            </tr>
            <tr>
                <th width="15%"><?= $attribute_labels['detail'] ?></th>
                <td width="85%" colspan="3"><?= nl2br($model->detail); ?></td>
            </tr>
            <tr>
                <th width="15%"><?= $attribute_labels['parking_type_id'] ?></th>
                <td width="35%"><?= (isset($model->parking_type_id)) ? $model->parkingType->name:'-'; ?></td>
            
                <!-- <th width="15%"><?= $attribute_labels['spending_type_id'] ?></th>
                <td width="35%"><?= (isset($model->spending_type_id)) ? $model->spendingType->name:'-'; ?></td> -->

                <th width="15%"><?= Yii::t('app', 'Latitude/Longitude') ?></th>
                <td width="35%"><?= BaseFunctions::latLong($model); ?></td>
            </tr>
            <tr><th width="15%"><?= $attribute_labels['url'] ?></th>
                <td width="35%"><?= (isset($model->url)) ? Html::a($model->url, Url::to($model->url, true), ['target'=>'_blank']) :'-'; ?></td>

                <th width="15%"><?= Yii::t('app', 'Status') ?></th>
                <td width="35%"><?= BaseFunctions::status($model->status); ?></td>
            </tr>
        </table>
    </div>
</div>

<div class="box box-success box-solid">
    <div class="box-header with-border">
        <h3 class="box-title"><i class="fa fa-sitemap"></i>&nbsp;&nbsp;<?php echo Yii::t('app', 'Place Category') ?></h3>
    </div>

    <div class="box-body">
        <div class="table-responsive">
            <table class="table table-bordered table-responsive">
                <?php if(!empty($placeCategories->category_id)) {

                    $categories = explode(",", $placeCategories->category_id);
                    foreach($categories as $key => $value) {
                        // get category name
                            $model_package = Category::findOne($value);
                            echo '<div class="col-xs-8 col-md-2">';
                            echo '<br><i class="fa fa-check-square-o"></i>&nbsp;&nbsp;' . $model_package->name;
                            echo '</div>';
                    }; 
                } else {
                    echo 'No category been saved';
                } ?>
            </table>
        </div>
    </div>
</div>

<div class="box box-success box-solid">
    <div class="box-header with-border">
        <h3 class="box-title"><i class="fa fa-bank"></i>&nbsp;&nbsp;<?php echo Yii::t('app', 'Place Islamic Element') ?></h3>
    </div>

    <div class="box-body">
        <div class="table-responsive">
            <table class="table table-bordered table-responsive">
                <?php if(!empty($placeElements->islamic_element_id)) {

                    $elements = explode(",", $placeElements->islamic_element_id);
                    foreach($elements as $key => $value) {
                            // get category name
                            $model_element = IslamicElements::findOne($value);
                            echo '<div class="col-xs-8 col-md-2">';
                            echo '<br><i class="fa fa-check-square-o"></i>&nbsp;&nbsp;' . $model_element->name;
                            echo '</div>';
                    }; 
                } else {
                    echo 'No islamic element been saved';
                } ?>
            </table>
        </div>
    </div>
</div>

<div class="box box-success box-solid collapsed-box">
    <div class="box-header with-border">
        <h3 class="box-title"><i class="fa fa-image"></i>&nbsp;&nbsp;<?php echo Yii::t('app', 'Place Photos') ?></h3>
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i></button>
        </div>
    </div>

    <div class="box-body" style="display: none;">
        <div class="table-responsive">
            <table class="table table-bordered table-striped table-responsive">
                <thead>
                    <tr>
                        <th width="5%" class="text-center"><?php echo Yii::t('app', 'No.'); ?></th>
                        <th width="35%"><?php echo Yii::t('app', 'File'); ?></th>
                        <th width="50%"><?php echo Yii::t('app', 'Detail'); ?></th>
                        <th width="10%" class="text-center"><?php echo Yii::t('app', 'Download'); ?></th>
                    </tr>
                </thead>

                <tbody>
                <?php if (count($images) == 0) { ?>
                    <tr>
                        <td colspan="4"><?php echo Yii::t('app', 'No Attachment') ?></td>
                    </tr>
                <?php } ?>
                <?php $bil=1; $path = null; foreach ($images as $image) { ?>
                    <tr>
                        <td class="text-center"><?php echo $bil; ?></td>
                        <td>
                            <?php if (isset($image)) {
                                $type = $image->file_type;
                                $path = Yii::$app->request->baseUrl . $image->file_path;

                                if (file_exists(\Yii::getAlias('@app/web') . DIRECTORY_SEPARATOR . $image->file_path )) {
                                    if ($type == 'application/pdf') {

                                        echo '<img src="'. Yii::$app->request->baseUrl .'/images/icon_pdf.png" width="250px;">';

                                    } else { ?>
                                        <button type="button"  data-toggle="modal" data-target="#modal-default<?= $bil; ?>">
                                            <img src=<?= $path; ?> width="280px;">
                                        </button>

                                        <div class="modal fade" id="modal-default<?= $bil; ?>" style="display: none;">
                                            <div class="modal-dialog">
                                                <br><br>
                                                <img src=<?= $path; ?> width="100%;">
                                            </div>
                                        </div>
                                    <?php }
                                } else {
                                    
                                    echo '<span class="label label-danger">'.Yii::t('app', 'Image not found') .'</span>';
                                }

                            } else {

                                echo Yii::t('app', 'No image attach');
                            } ?>
                        </td>
                        <td><?php echo $image->detail; ?></td>
                        <td class="text-center">
                            <?php echo Html::a('<i class="fa fa-download"></i>', ['download', 'id' => $image->id], [
                                'class' => 'btn btn-default', 'data-method' => 'post']) ?>
                        </td>
                    </tr>
                    <?php $bil++;} ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="box box-success box-solid">
    <div class="box-header with-border">
        <h3 class="box-title"><i class="fa fa-tachometer"></i>&nbsp;&nbsp;<?php echo Yii::t('app', 'Place Operation Hour') ?></h3>
    </div>

    <div class="box-body">
        <div class="table-responsive">
            <div class="col-md-6">
                <table class="table table-bordered table-striped table-responsive">
                    <thead>
                        <tr>
                            <th style="width: 30%;"><?= Yii::t('app', 'Day'); ?></th>
                            <th style="width: 20%; text-align: center"><?= Yii::t('app', 'Start Time'); ?></th>
                            <th style="width: 20%; text-align: center"><?= Yii::t('app', 'Close Time'); ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if($model->status == 4 || $model->status == 5) { ?>
                            <tr>
                                <td colspan="3"><?php echo Yii::t('app', 'Place temporarily closed/closed') ?></td>
                            </tr>
                        <?php } else { ?>

                        <?php if (count($operationHours) == 0) { ?>
                            <tr>
                                <td colspan="3"><?php echo Yii::t('app', 'No Data Found') ?></td>
                            </tr>
                        <?php } else { ?>
                            <?php foreach ($operationHours as $hour) { ?>
                                <tr>
                                    <td><?= $hour->day->name; ?></td>
                                    <td class="text-center"><?= $hour->start_time; ?></td>
                                    <td class="text-center"><?= $hour->end_time; ?></td>
                                </tr>
                        <?php }; }; } ?>
                    </tbody>
                </table>
            </div>

            <div class="col-md-6">
                <table class="table table-bordered table-striped table-responsive">
                    <thead>
                        <tr>
                            <th style="width: 30%;"><?= Yii::t('app', 'Operation Hour Remark'); ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <?php if(!empty($model->operating_remark)) { ?>
                                <td><?= $model->operating_remark; ?></td>
                            <?php } else { ?>
                                <td><?= Yii::t('app', 'No data been saved'); ?></td>
                            <?php } ?>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<?php echo Html::a('<i class="fa fa-arrow-left"></i> ' . Yii::t('app', 'Back'), ['index'], ['class' => 'btn btn-warning']) ?>

<?php echo Html::a('<i class="fa fa-pencil"></i> ' . Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>

<?php echo Html::a('<i class="fa fa-trash"></i> ' . Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
    'class' => 'btn btn-danger', 
    'data' => [
        'confirm' => Yii::t('app', 'Are you sure you want to delete this data?'),
        'method' => 'post',
    ]
]) ?>